[font.offset]
x = 0
y = 0

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"

[font.bold]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold"

[font.italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Oblique"

[font.bold_italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold Oblique"
