[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".local/share/zap"]
    type = "git-repo"
    url = "https://github.com/zap-zsh/zap.git"
    refreshPeriod = "168h"
    [".local/share/zap".clone]
        args = ["-b", "master"]
[".config/qBittorrent/themes/catppuccin-mocha.qbtheme"]
    type = "file"
    url = "https://github.com/catppuccin/qbittorrent/releases/latest/download/catppuccin-mocha.qbtheme"
    refreshPeriod = "168h"
